### ISSUE TITLE
seems dead?

### ISSUE THREAD

**Issue by evanrich** [wnielson/Plex-Bandwidth-Monitor#1]
This would be an awesome monitoring tool, but last update was a year ago...seems it's dead?  Dev if you read this, I'd be happy to donate a chunk of money to have this finished (including tracking transcoded streams).   I'd like to be able to see how much bandwidth my plex users consume

**Comment by wnielson** [comment]
I wouldn't say it is dead, it has just been on hiatus.  I'd be interested in hearing how you would like to use this.  I have some ideas for things I'd like to add, including better logging and configuration.

**Comment by evanrich** [comment]
@wnielson  thanks for the reply :)   I already use plexpy for tracking of usage by user, and while it works pretty well, it does NOT record traffic per user.  I'm completely fine using a split system for this, and this is how I'd envision usage, at least in my case:

I currently have influxdb + grafana set up in an ESX environment at home to keep track over everything in my house.  From System metrics in my servers to how much power my house/devices use (and what it costs me).   Ideally, this could plug in/export to influx so that the following could be accomplished:

This script monitors traffic as you describe, looking at outgoing streams and using pcaps to measure bytes.   This info gets fed into influx with a format containing IP/USERname, and bytes sent.    Influx+grafana could then be used to turn this into a BPS graph, and with some magic, a cumulative total.   I suppose your script could do that as well, possibly with the option to export to sqlite/mysql/etc, but having the option to export to influx would allow a "sum" of all bytes sent (if you're only recording the # of bytes sent per-pcap).    This would then allow a graph/chart showing bandwidth consumed over X time per user.    

I could use something like this because I currently have a data cap that I bump real close to, so knowing who consumes the most bandwidth would allow me to trim usage if necessary.

**Comment by wnielson** [comment]
I just pushed some new code.  `pcap` is no longer required and session stats are now written to a sqlite database.  I'm planning on adding support for other databases so that a remote db can be used instead of just a local sqlite db.
